const { v4: uuidv4 } = require('uuid');

exports.seed = async function(knex) {
  // Delete existing staff entries
  await knex('staff').del();

  const now = new Date();
  const oneYearAgo = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate());
  const twoYearsAgo = new Date(now.getFullYear() - 2, now.getMonth(), now.getDate());
  const fiveYearsAgo = new Date(now.getFullYear() - 5, now.getMonth(), now.getDate());

  // Sample staff data with comprehensive Nigerian fields
  const staffMembers = [
    {
      staff_id: 'STF001',
      first_name: 'Adebayo',
      middle_name: 'Oluwaseun',
      last_name: 'Ogunleye',
      email: 'adebayo.ogunleye@institution.edu.ng',
      phone: '+2348012345678',
      alternate_phone: '+2348123456789',
      date_of_birth: '1985-03-15',
      gender: 'male',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '12345678901',
      bvn: '98765432101',
      state_of_origin: 'Lagos',
      lga_of_origin: 'Ikeja',
      current_address: '45 Allen Avenue, Ikeja, Lagos',
      permanent_address: '12 Ogunleye Street, Mushin, Lagos',
      department: 'Academic Affairs',
      position: 'Dean of Students',
      job_title: 'Senior Academic Officer',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: fiveYearsAgo,
      confirmation_date: new Date(fiveYearsAgo.getFullYear(), fiveYearsAgo.getMonth() + 6, fiveYearsAgo.getDate()),
      reporting_to: 'Vice Chancellor',
      highest_qualification: 'PhD in Education',
      institution_attended: 'University of Lagos',
      years_of_experience: 15,
      certifications: ['ACCA', 'PMP'],
      specializations: ['Educational Administration', 'Student Affairs'],
      basic_salary: 350000,
      salary_grade: 'Level 14',
      salary_step: 'Step 8',
      bank_name: 'First Bank of Nigeria',
      account_number: '1234567890',
      account_name: 'Adebayo Oluwaseun Ogunleye',
      pension_pin: 'PEN123456',
      tax_id: 'TAX987654',
      next_of_kin_name: 'Adeola Ogunleye',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348011111111',
      next_of_kin_address: '45 Allen Avenue, Ikeja, Lagos',
      blood_group: 'O+',
      genotype: 'AA',
      languages_spoken: ['English', 'Yoruba'],
      health_conditions: 'None',
      allergies: 'Penicillin',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 2, 0, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF002',
      first_name: 'Chidinma',
      middle_name: 'Grace',
      last_name: 'Nwosu',
      email: 'chidinma.nwosu@institution.edu.ng',
      phone: '+2348023456789',
      alternate_phone: '+2348134567890',
      date_of_birth: '1990-07-22',
      gender: 'female',
      marital_status: 'single',
      nationality: 'Nigerian',
      nin: '23456789012',
      bvn: '87654321012',
      state_of_origin: 'Anambra',
      lga_of_origin: 'Awka North',
      current_address: '23 Independence Layout, Enugu',
      permanent_address: '7 Nwosu Compound, Awka, Anambra',
      department: 'IT Support',
      position: 'IT Manager',
      job_title: 'Senior Systems Administrator',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: twoYearsAgo,
      confirmation_date: new Date(twoYearsAgo.getFullYear(), twoYearsAgo.getMonth() + 6, twoYearsAgo.getDate()),
      reporting_to: 'Director of ICT',
      highest_qualification: 'M.Sc Computer Science',
      institution_attended: 'University of Nigeria, Nsukka',
      years_of_experience: 8,
      certifications: ['CCNA', 'AWS Solutions Architect', 'CompTIA Security+'],
      specializations: ['Network Administration', 'Cloud Computing', 'Cybersecurity'],
      basic_salary: 280000,
      salary_grade: 'Level 12',
      salary_step: 'Step 5',
      bank_name: 'Zenith Bank',
      account_number: '2345678901',
      account_name: 'Chidinma Grace Nwosu',
      pension_pin: 'PEN234567',
      tax_id: 'TAX876543',
      next_of_kin_name: 'Emmanuel Nwosu',
      next_of_kin_relationship: 'Father',
      next_of_kin_phone: '+2348022222222',
      next_of_kin_address: '7 Nwosu Compound, Awka, Anambra',
      blood_group: 'A+',
      genotype: 'AS',
      languages_spoken: ['English', 'Igbo'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 1, 6, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF003',
      first_name: 'Ibrahim',
      middle_name: 'Mohammed',
      last_name: 'Abubakar',
      email: 'ibrahim.abubakar@institution.edu.ng',
      phone: '+2348034567890',
      alternate_phone: '+2348145678901',
      date_of_birth: '1982-11-08',
      gender: 'male',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '34567890123',
      bvn: '76543210123',
      state_of_origin: 'Kano',
      lga_of_origin: 'Kano Municipal',
      current_address: '89 Zaria Road, Kano',
      permanent_address: '34 Abubakar Lane, Sabon Gari, Kano',
      department: 'Finance',
      position: 'Chief Accountant',
      job_title: 'Senior Financial Officer',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: fiveYearsAgo,
      confirmation_date: new Date(fiveYearsAgo.getFullYear(), fiveYearsAgo.getMonth() + 6, fiveYearsAgo.getDate()),
      reporting_to: 'Bursar',
      highest_qualification: 'M.Sc Accounting',
      institution_attended: 'Ahmadu Bello University',
      years_of_experience: 18,
      certifications: ['ICAN', 'CPA'],
      specializations: ['Financial Management', 'Auditing', 'Tax Planning'],
      basic_salary: 320000,
      salary_grade: 'Level 13',
      salary_step: 'Step 7',
      bank_name: 'United Bank for Africa',
      account_number: '3456789012',
      account_name: 'Ibrahim Mohammed Abubakar',
      pension_pin: 'PEN345678',
      tax_id: 'TAX765432',
      next_of_kin_name: 'Aisha Abubakar',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348033333333',
      next_of_kin_address: '89 Zaria Road, Kano',
      blood_group: 'B+',
      genotype: 'AA',
      languages_spoken: ['English', 'Hausa'],
      health_conditions: 'Hypertension (controlled)',
      allergies: 'None',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 2, 3, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF004',
      first_name: 'Funmilayo',
      middle_name: 'Abosede',
      last_name: 'Adeyemi',
      email: 'funmilayo.adeyemi@institution.edu.ng',
      phone: '+2348045678901',
      date_of_birth: '1988-05-19',
      gender: 'female',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '45678901234',
      bvn: '65432101234',
      state_of_origin: 'Osun',
      lga_of_origin: 'Ife Central',
      current_address: '56 Ring Road, Ibadan, Oyo',
      permanent_address: '19 Adeyemi Compound, Ile-Ife, Osun',
      department: 'Human Resources',
      position: 'HR Manager',
      job_title: 'Principal HR Officer',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 3, 8, 1),
      confirmation_date: new Date(now.getFullYear() - 3, 2, 1),
      reporting_to: 'Director of HR',
      highest_qualification: 'M.Sc Human Resource Management',
      institution_attended: 'Obafemi Awolowo University',
      years_of_experience: 10,
      certifications: ['CIPM', 'SHRM-CP'],
      specializations: ['Recruitment', 'Employee Relations', 'Performance Management'],
      basic_salary: 270000,
      salary_grade: 'Level 12',
      salary_step: 'Step 4',
      bank_name: 'GTBank',
      account_number: '4567890123',
      account_name: 'Funmilayo Abosede Adeyemi',
      pension_pin: 'PEN456789',
      tax_id: 'TAX654321',
      next_of_kin_name: 'Adekunle Adeyemi',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348044444444',
      next_of_kin_address: '56 Ring Road, Ibadan, Oyo',
      blood_group: 'AB+',
      genotype: 'AA',
      languages_spoken: ['English', 'Yoruba'],
      health_conditions: 'None',
      allergies: 'Shellfish',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 1, 0, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF005',
      first_name: 'Emeka',
      middle_name: 'Victor',
      last_name: 'Okafor',
      email: 'emeka.okafor@institution.edu.ng',
      phone: '+2348056789012',
      date_of_birth: '1992-09-30',
      gender: 'male',
      marital_status: 'single',
      nationality: 'Nigerian',
      nin: '56789012345',
      bvn: '54321012345',
      state_of_origin: 'Imo',
      lga_of_origin: 'Owerri Municipal',
      current_address: '78 Wetheral Road, Owerri, Imo',
      permanent_address: '23 Okafor Street, Owerri, Imo',
      department: 'Library',
      position: 'Senior Librarian',
      job_title: 'Library Officer',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: oneYearAgo,
      confirmation_date: new Date(oneYearAgo.getFullYear(), oneYearAgo.getMonth() + 6, oneYearAgo.getDate()),
      reporting_to: 'Chief Librarian',
      highest_qualification: 'M.Lib.Sc',
      institution_attended: 'Federal University of Technology, Owerri',
      years_of_experience: 5,
      certifications: ['Certified Librarian'],
      specializations: ['Digital Libraries', 'Information Management'],
      basic_salary: 220000,
      salary_grade: 'Level 10',
      salary_step: 'Step 2',
      bank_name: 'Access Bank',
      account_number: '5678901234',
      account_name: 'Emeka Victor Okafor',
      pension_pin: 'PEN567890',
      tax_id: 'TAX543210',
      next_of_kin_name: 'Ngozi Okafor',
      next_of_kin_relationship: 'Mother',
      next_of_kin_phone: '+2348055555555',
      next_of_kin_address: '23 Okafor Street, Owerri, Imo',
      blood_group: 'O-',
      genotype: 'AA',
      languages_spoken: ['English', 'Igbo'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF006',
      first_name: 'Blessing',
      middle_name: 'Chiamaka',
      last_name: 'Nnamani',
      email: 'blessing.nnamani@institution.edu.ng',
      phone: '+2348067890123',
      date_of_birth: '1987-02-14',
      gender: 'female',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '67890123456',
      bvn: '43210123456',
      state_of_origin: 'Enugu',
      lga_of_origin: 'Enugu North',
      current_address: '34 Presidential Road, Enugu',
      permanent_address: '12 Nnamani Avenue, Enugu',
      department: 'Student Services',
      position: 'Student Affairs Officer',
      job_title: 'Senior Student Services Officer',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 4, 3, 15),
      confirmation_date: new Date(now.getFullYear() - 4, 9, 15),
      reporting_to: 'Dean of Student Affairs',
      highest_qualification: 'M.Ed Guidance and Counseling',
      institution_attended: 'University of Nigeria, Nsukka',
      years_of_experience: 12,
      certifications: ['Licensed Counselor', 'Student Development Professional'],
      specializations: ['Student Counseling', 'Career Guidance', 'Student Welfare'],
      basic_salary: 260000,
      salary_grade: 'Level 11',
      salary_step: 'Step 6',
      bank_name: 'Ecobank',
      account_number: '6789012345',
      account_name: 'Blessing Chiamaka Nnamani',
      pension_pin: 'PEN678901',
      tax_id: 'TAX432109',
      next_of_kin_name: 'Chukwuemeka Nnamani',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348066666666',
      next_of_kin_address: '34 Presidential Road, Enugu',
      blood_group: 'A-',
      genotype: 'AA',
      languages_spoken: ['English', 'Igbo'],
      health_conditions: 'None',
      allergies: 'Nuts',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 1, 8, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF007',
      first_name: 'Yusuf',
      middle_name: 'Ahmed',
      last_name: 'Bello',
      email: 'yusuf.bello@institution.edu.ng',
      phone: '+2348078901234',
      date_of_birth: '1984-12-03',
      gender: 'male',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '78901234567',
      bvn: '32101234567',
      state_of_origin: 'Kaduna',
      lga_of_origin: 'Kaduna North',
      current_address: '90 Constitution Road, Kaduna',
      permanent_address: '45 Bello Close, Kaduna',
      department: 'Maintenance',
      position: 'Facility Manager',
      job_title: 'Chief Maintenance Officer',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 6, 1, 1),
      confirmation_date: new Date(now.getFullYear() - 6, 7, 1),
      reporting_to: 'Director of Works',
      highest_qualification: 'HND Building Technology',
      institution_attended: 'Kaduna Polytechnic',
      years_of_experience: 20,
      certifications: ['Facility Management Professional', 'Building Maintenance'],
      specializations: ['Building Maintenance', 'Facility Operations', 'Safety Management'],
      basic_salary: 240000,
      salary_grade: 'Level 11',
      salary_step: 'Step 3',
      bank_name: 'Stanbic IBTC',
      account_number: '7890123456',
      account_name: 'Yusuf Ahmed Bello',
      pension_pin: 'PEN789012',
      tax_id: 'TAX321098',
      next_of_kin_name: 'Hauwa Bello',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348077777777',
      next_of_kin_address: '90 Constitution Road, Kaduna',
      blood_group: 'B-',
      genotype: 'AS',
      languages_spoken: ['English', 'Hausa'],
      health_conditions: 'Diabetes (managed)',
      allergies: 'None',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 3, 5, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF008',
      first_name: 'Ngozi',
      middle_name: 'Ifeyinwa',
      last_name: 'Eze',
      email: 'ngozi.eze@institution.edu.ng',
      phone: '+2348089012345',
      date_of_birth: '1991-06-25',
      gender: 'female',
      marital_status: 'single',
      nationality: 'Nigerian',
      nin: '89012345678',
      bvn: '21012345678',
      state_of_origin: 'Ebonyi',
      lga_of_origin: 'Abakaliki',
      current_address: '67 Ogui Road, Enugu',
      permanent_address: '28 Eze Compound, Abakaliki, Ebonyi',
      department: 'Administration',
      position: 'Administrative Officer',
      job_title: 'Senior Administrative Assistant',
      employment_type: 'full-time',
      employment_status: 'on-leave',
      hire_date: twoYearsAgo,
      confirmation_date: new Date(twoYearsAgo.getFullYear(), twoYearsAgo.getMonth() + 6, twoYearsAgo.getDate()),
      reporting_to: 'Registrar',
      highest_qualification: 'B.Sc Public Administration',
      institution_attended: 'Ebonyi State University',
      years_of_experience: 6,
      certifications: ['Office Management Professional'],
      specializations: ['Office Administration', 'Records Management'],
      basic_salary: 200000,
      salary_grade: 'Level 9',
      salary_step: 'Step 3',
      bank_name: 'Fidelity Bank',
      account_number: '8901234567',
      account_name: 'Ngozi Ifeyinwa Eze',
      pension_pin: 'PEN890123',
      tax_id: 'TAX210987',
      next_of_kin_name: 'Chidi Eze',
      next_of_kin_relationship: 'Brother',
      next_of_kin_phone: '+2348088888888',
      next_of_kin_address: '28 Eze Compound, Abakaliki, Ebonyi',
      blood_group: 'O+',
      genotype: 'AA',
      languages_spoken: ['English', 'Igbo'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 30,
      sick_leave_days: 15,
      casual_leave_days: 7,
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    // Non-Academic Staff Members
    {
      staff_id: 'STF009',
      first_name: 'Musa',
      middle_name: 'Tanko',
      last_name: 'Ibrahim',
      email: 'musa.ibrahim@institution.edu.ng',
      phone: '+2348090123456',
      date_of_birth: '1980-04-18',
      gender: 'male',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '90123456789',
      bvn: '10123456789',
      state_of_origin: 'Niger',
      lga_of_origin: 'Suleja',
      current_address: '15 Madalla Road, Suleja, Niger',
      permanent_address: '8 Ibrahim Street, Suleja, Niger',
      department: 'Non-Academic Staff',
      position: 'Chief Security Officer',
      job_title: 'Security Supervisor',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 8, 2, 1),
      confirmation_date: new Date(now.getFullYear() - 8, 8, 1),
      reporting_to: 'Director of Security',
      highest_qualification: 'SSCE',
      institution_attended: 'Government Secondary School, Suleja',
      years_of_experience: 22,
      certifications: ['Security Management Certificate'],
      specializations: ['Campus Security', 'Surveillance Operations'],
      basic_salary: 120000,
      salary_grade: 'Level 6',
      salary_step: 'Step 8',
      bank_name: 'Union Bank',
      account_number: '9012345678',
      account_name: 'Musa Tanko Ibrahim',
      pension_pin: 'PEN901234',
      tax_id: 'TAX109876',
      next_of_kin_name: 'Fatima Ibrahim',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348099999999',
      next_of_kin_address: '15 Madalla Road, Suleja, Niger',
      blood_group: 'O+',
      genotype: 'AA',
      languages_spoken: ['English', 'Hausa', 'Nupe'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 21,
      sick_leave_days: 12,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 4, 2, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF010',
      first_name: 'Patience',
      middle_name: 'Nneka',
      last_name: 'Okonkwo',
      email: 'patience.okonkwo@institution.edu.ng',
      phone: '+2348091234567',
      date_of_birth: '1989-08-12',
      gender: 'female',
      marital_status: 'single',
      nationality: 'Nigerian',
      nin: '01234567890',
      bvn: '98012345678',
      state_of_origin: 'Abia',
      lga_of_origin: 'Umuahia North',
      current_address: '42 Library Road, Umuahia, Abia',
      permanent_address: '18 Okonkwo Compound, Umuahia, Abia',
      department: 'Non-Academic Staff',
      position: 'Cleaning Supervisor',
      job_title: 'Senior Janitor',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 5, 6, 15),
      confirmation_date: new Date(now.getFullYear() - 5, 0, 15),
      reporting_to: 'Facility Manager',
      highest_qualification: 'SSCE',
      institution_attended: 'Community Secondary School, Umuahia',
      years_of_experience: 10,
      certifications: ['Housekeeping Certificate'],
      specializations: ['Facility Cleaning', 'Hygiene Management'],
      basic_salary: 80000,
      salary_grade: 'Level 4',
      salary_step: 'Step 5',
      bank_name: 'First Bank of Nigeria',
      account_number: '0123456789',
      account_name: 'Patience Nneka Okonkwo',
      pension_pin: 'PEN012345',
      tax_id: 'TAX098765',
      next_of_kin_name: 'Chukwudi Okonkwo',
      next_of_kin_relationship: 'Father',
      next_of_kin_phone: '+2348091111111',
      next_of_kin_address: '18 Okonkwo Compound, Umuahia, Abia',
      blood_group: 'A+',
      genotype: 'AA',
      languages_spoken: ['English', 'Igbo'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 21,
      sick_leave_days: 12,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 2, 6, 15),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF011',
      first_name: 'Olumide',
      middle_name: 'Kayode',
      last_name: 'Adeleke',
      email: 'olumide.adeleke@institution.edu.ng',
      phone: '+2348092345678',
      date_of_birth: '1986-01-29',
      gender: 'male',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '12345098765',
      bvn: '87012345678',
      state_of_origin: 'Ogun',
      lga_of_origin: 'Abeokuta South',
      current_address: '71 Ita Eko, Abeokuta, Ogun',
      permanent_address: '25 Adeleke Lane, Abeokuta, Ogun',
      department: 'Non-Academic Staff',
      position: 'Transport Officer',
      job_title: 'Senior Driver',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 7, 9, 1),
      confirmation_date: new Date(now.getFullYear() - 7, 3, 1),
      reporting_to: 'Transport Manager',
      highest_qualification: 'SSCE',
      institution_attended: 'Baptist Boys High School, Abeokuta',
      years_of_experience: 16,
      certifications: ['Professional Driving License', 'Defensive Driving Certificate'],
      specializations: ['Commercial Driving', 'Vehicle Maintenance'],
      basic_salary: 110000,
      salary_grade: 'Level 5',
      salary_step: 'Step 7',
      bank_name: 'Zenith Bank',
      account_number: '1234509876',
      account_name: 'Olumide Kayode Adeleke',
      pension_pin: 'PEN123450',
      tax_id: 'TAX987012',
      next_of_kin_name: 'Folake Adeleke',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348092222222',
      next_of_kin_address: '71 Ita Eko, Abeokuta, Ogun',
      blood_group: 'B+',
      genotype: 'AS',
      languages_spoken: ['English', 'Yoruba'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 21,
      sick_leave_days: 12,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 3, 9, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF012',
      first_name: 'Aisha',
      middle_name: 'Zainab',
      last_name: 'Yusuf',
      email: 'aisha.yusuf@institution.edu.ng',
      phone: '+2348093456789',
      date_of_birth: '1993-11-05',
      gender: 'female',
      marital_status: 'married',
      nationality: 'Nigerian',
      nin: '23450987654',
      bvn: '76012345678',
      state_of_origin: 'Sokoto',
      lga_of_origin: 'Sokoto North',
      current_address: '38 Sultan Abubakar Road, Sokoto',
      permanent_address: '14 Yusuf Close, Sokoto',
      department: 'Non-Academic Staff',
      position: 'Catering Officer',
      job_title: 'Head Cook',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 3, 4, 1),
      confirmation_date: new Date(now.getFullYear() - 3, 10, 1),
      reporting_to: 'Catering Manager',
      highest_qualification: 'NCE Home Economics',
      institution_attended: 'Federal College of Education, Sokoto',
      years_of_experience: 8,
      certifications: ['Food Safety Certificate', 'Catering Management'],
      specializations: ['Institutional Catering', 'Food Preparation', 'Menu Planning'],
      basic_salary: 95000,
      salary_grade: 'Level 5',
      salary_step: 'Step 3',
      bank_name: 'GTBank',
      account_number: '2345098765',
      account_name: 'Aisha Zainab Yusuf',
      pension_pin: 'PEN234509',
      tax_id: 'TAX870123',
      next_of_kin_name: 'Usman Yusuf',
      next_of_kin_relationship: 'Spouse',
      next_of_kin_phone: '+2348093333333',
      next_of_kin_address: '38 Sultan Abubakar Road, Sokoto',
      blood_group: 'O-',
      genotype: 'AA',
      languages_spoken: ['English', 'Hausa', 'Fulfulde'],
      health_conditions: 'None',
      allergies: 'None',
      annual_leave_days: 21,
      sick_leave_days: 12,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 1, 4, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    },
    {
      staff_id: 'STF013',
      first_name: 'Chukwudi',
      middle_name: 'Benjamin',
      last_name: 'Onyeka',
      email: 'chukwudi.onyeka@institution.edu.ng',
      phone: '+2348094567890',
      date_of_birth: '1988-07-21',
      gender: 'male',
      marital_status: 'single',
      nationality: 'Nigerian',
      nin: '34509876543',
      bvn: '65012345678',
      state_of_origin: 'Delta',
      lga_of_origin: 'Warri South',
      current_address: '52 Effurun-Sapele Road, Warri, Delta',
      permanent_address: '30 Onyeka Avenue, Warri, Delta',
      department: 'Non-Academic Staff',
      position: 'Groundskeeper',
      job_title: 'Gardener/Landscaper',
      employment_type: 'full-time',
      employment_status: 'active',
      hire_date: new Date(now.getFullYear() - 4, 1, 1),
      confirmation_date: new Date(now.getFullYear() - 4, 7, 1),
      reporting_to: 'Facility Manager',
      highest_qualification: 'SSCE',
      institution_attended: 'Hussey College, Warri',
      years_of_experience: 12,
      certifications: ['Horticultural Training Certificate'],
      specializations: ['Landscaping', 'Garden Maintenance', 'Plant Care'],
      basic_salary: 85000,
      salary_grade: 'Level 4',
      salary_step: 'Step 4',
      bank_name: 'Access Bank',
      account_number: '3450987654',
      account_name: 'Chukwudi Benjamin Onyeka',
      pension_pin: 'PEN345098',
      tax_id: 'TAX760123',
      next_of_kin_name: 'Ifeoma Onyeka',
      next_of_kin_relationship: 'Sister',
      next_of_kin_phone: '+2348094444444',
      next_of_kin_address: '30 Onyeka Avenue, Warri, Delta',
      blood_group: 'AB-',
      genotype: 'AA',
      languages_spoken: ['English', 'Igbo', 'Urhobo'],
      health_conditions: 'None',
      allergies: 'Pollen',
      annual_leave_days: 21,
      sick_leave_days: 12,
      casual_leave_days: 7,
      last_promotion_date: new Date(now.getFullYear() - 2, 1, 1),
      last_appraisal_date: new Date(now.getFullYear(), 0, 1),
      created_at: now,
      updated_at: now
    }
  ];

  // Insert staff members
  await knex('staff').insert(staffMembers);

  console.log('✅ Sample staff data seeded successfully');
};
